'use strict';
const get = id => document.getElementById(id);
const TOTAL=QUESTIONS.length, TARGET=Math.ceil(TOTAL*.8), STORAGE_KEY='iot-topic1-short-answer-v1';
const blankRecord=()=>({status:'unanswered',answer:'',attempts:0,hints:0,spellingAccepted:false});
let records=QUESTIONS.map(blankRecord), current=0, view='question', retryQueue=null, saveAvailable=true, justReached=false;
try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');if(saved?.version===1&&Array.isArray(saved.records)){records=QUESTIONS.map((q,i)=>{const r=saved.records[i];if(!r||r.id!==q.id)return blankRecord();return {status:['unanswered','incorrect','correct'].includes(r.status)?r.status:'unanswered',answer:typeof r.answer==='string'?r.answer.slice(0,180):'',attempts:Number.isInteger(r.attempts)&&r.attempts>=0?Math.min(100000,r.attempts):0,hints:Number.isInteger(r.hints)&&r.hints>=0?Math.min(100000,r.hints):0,spellingAccepted:r.spellingAccepted===true};});if(Number.isInteger(saved.current)&&saved.current>=0&&saved.current<TOTAL)current=saved.current;if(saved.view==='overview')view='overview';}}catch{saveAvailable=false;}
function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify({version:1,current,view,records:records.map((r,i)=>({...r,id:QUESTIONS[i].id}))}));}catch{saveAvailable=false;}get('save-status').textContent=saveAvailable?'Progress saved on this device':'Progress kept for this session';}
function correctCount(){return records.filter(r=>r.status==='correct').length;}
function normalizeAnswer(raw){let value=raw.toLowerCase().normalize('NFKC').replace(/[’']/g,"'").trim();value=value.split(/\bbecause\b|\bas it\b|\bsince it\b/)[0];value=value.replace(/[_–—-]/g,' ').replace(/[.,!?;:()]/g,' ').replace(/\s+/g,' ').trim();const prefix=/^(?:i think(?: that)?|the correct answer is|the answer is|my answer is|this is|it is|it would be|the capability is|the component is|the process is|a|an|the)\s+/;for(let i=0;i<5&&prefix.test(value);i++)value=value.replace(prefix,'').trim();return value;}
function spellingDistance(a,b){const matrix=Array.from({length:a.length+1},()=>Array(b.length+1).fill(0));for(let i=0;i<=a.length;i++)matrix[i][0]=i;for(let j=0;j<=b.length;j++)matrix[0][j]=j;for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++){matrix[i][j]=Math.min(matrix[i-1][j]+1,matrix[i][j-1]+1,matrix[i-1][j-1]+(a[i-1]===b[j-1]?0:1));if(i>1&&j>1&&a[i-1]===b[j-2]&&a[i-2]===b[j-1])matrix[i][j]=Math.min(matrix[i][j],matrix[i-2][j-2]+1);}return matrix[a.length][b.length];}
const knownTerms=new Set(QUESTIONS.flatMap(q=>q.answers).map(normalizeAnswer));
const ordinaryTerms=new Set(['cat','dog','art','eat','car','ant','house','room','light','sensor','cloud','data','speed','amount','quality','trust','memory','processing','network','storage','temperature','humidity','volume','value','variety','veracity','velocity']);
function gradeAnswer(question,raw){const answer=normalizeAnswer(raw);if(!answer)return {correct:false,empty:true};if(/\b(?:no|not|never|without)\b|n't\b/.test(answer))return {correct:false,formatHint:'State the concept you choose directly. Avoid negating it or listing alternatives.'};if(/\b(?:or|and)\b/.test(answer))return {correct:false,formatHint:'Choose one concept for this scenario. A short concept name is enough.'};const expected=question.answers.map(normalizeAnswer);if(expected.includes(answer))return {correct:true,spellingAccepted:false};if(knownTerms.has(answer)||ordinaryTerms.has(answer))return {correct:false};if(answer.split(' ').length>6)return {correct:false,formatHint:'Use the concept name as your answer. A short phrase is enough.'};for(const accepted of expected){const inputWords=answer.split(' '),expectedWords=accepted.split(' ');if(inputWords.length!==expectedWords.length)continue;let totalEdits=0,matched=true;for(let i=0;i<inputWords.length;i++){const a=inputWords[i],b=expectedWords[i];if(a===b)continue;const distance=spellingDistance(a,b);const shortTranspose=b.length===3&&a.length===3&&[...a].sort().join('')===[...b].sort().join('')&&distance===1;const allowance=b.length>=7?2:b.length>=4?1:shortTranspose?1:0;if(a.length<3||distance>allowance){matched=false;break;}totalEdits+=distance;}if(matched&&totalEdits>0&&totalEdits<=2)return {correct:true,spellingAccepted:true};}return {correct:false};}
function feedback(title,message,kind='hint'){const container=get('feedback');container.hidden=false;container.className='feedback '+(kind==='correct'?'correct':kind==='info'?'info':'');container.replaceChildren();const strong=document.createElement('strong');strong.textContent=title;const p=document.createElement('p');p.textContent=message;container.append(strong,p);}
function hintFor(record,question){return question.hints[Math.min(2,Math.max(record.attempts,record.hints,1)-1)];}
function updateScore(){const n=correctCount();get('mini-score').textContent=`${n} / ${TOTAL} correct`;get('mini-fill').style.width=(n/TOTAL*100)+'%';get('question-status').textContent=n>=TARGET?'80% target reached. You can keep improving.':'Target: 12 correct (80%). You can return to any question.';}
function renderQuestion(){const q=QUESTIONS[current],r=records[current];justReached=false;get('question-position').textContent=`QUESTION ${String(current+1).padStart(2,'0')} OF ${TOTAL}`;get('graphic-tag').textContent=q.tag;get('question-graphic').innerHTML=graphs[q.graphic];get('graphic-caption').textContent=q.caption;document.body.classList.toggle('simple-first-question',current===0);get('question-title').textContent=current===0?'A classroom temperature sensor sends readings. Which IoT ecosystem building block is it?':q.title;get('question-prompt').textContent=q.prompt;get('answer').value=r.answer;get('answer').disabled=r.status==='correct';get('submit-answer').disabled=r.status==='correct';get('submit-answer').innerHTML=r.status==='correct'?'Already correct ✓':'Check my answer <span>↗</span>';get('hint-button').hidden=r.status==='correct';get('attempt-count').textContent=r.attempts?`${r.attempts} ${r.attempts===1?'submission':'submissions'}`:'Not submitted yet';get('feedback').hidden=true;get('retry-note').hidden=true;get('next-question').hidden=r.attempts===0;get('next-question').textContent=current===TOTAL-1?'See score overview →':'Next question →';get('previous-question').disabled=current===0;get('skip-question').textContent=r.status==='correct'?'Continue →':'Leave this for later →';if(r.status==='correct')feedback('Correct — keep going.',r.spellingAccepted?'Your intended term was clear. A small spelling slip was accepted.':'You identified the concept in this scenario.','correct');else if(r.status==='incorrect'){feedback('Not yet — use this hint.',hintFor(r,q));get('retry-note').hidden=false;}updateScore();}
function showView(nextView){view=nextView;document.body.classList.toggle('question-mode',view==='question');get('question-view').hidden=view!=='question';get('overview-view').hidden=view!=='overview';get('practice-tab').classList.toggle('active',view==='question');get('overview-tab').classList.toggle('active',view==='overview');get('practice-tab').toggleAttribute('aria-current',view==='question');get('overview-tab').toggleAttribute('aria-current',view==='overview');const active=get(view==='question'?'practice-tab':'overview-tab');active.setAttribute('aria-current','page');if(view==='overview')renderOverview();else renderQuestion();save();}
function openQuestion(index){current=index;showView('question');get('question-view').scrollIntoView({block:'start',behavior:'instant'});get('question-title').setAttribute('tabindex','-1');get('question-title').focus({preventScroll:true});}
function advance(){if(justReached){showView('overview');return;}if(retryQueue){const rest=retryQueue.filter(i=>i!==current&&records[i].status!=='correct');if(rest.length){retryQueue=rest;openQuestion(rest[0]);}else{retryQueue=null;showView('overview');}}else if(current<TOTAL-1)openQuestion(current+1);else showView('overview');}
get('answer-form').addEventListener('submit',event=>{event.preventDefault();const q=QUESTIONS[current],r=records[current];if(r.status==='correct')return;const raw=get('answer').value.trim();const result=gradeAnswer(q,raw);if(result.empty){feedback('Add a short answer first.','Type one concept name, then check it. You can ask for a starting hint.','info');get('answer').focus();return;}const before=correctCount();r.answer=raw;r.attempts++;r.status=result.correct?'correct':'incorrect';r.spellingAccepted=result.spellingAccepted===true;get('attempt-count').textContent=`${r.attempts} ${r.attempts===1?'submission':'submissions'}`;get('next-question').hidden=false;get('retry-note').hidden=result.correct;if(result.correct){get('answer').disabled=true;get('submit-answer').disabled=true;get('submit-answer').textContent='Already correct ✓';get('hint-button').hidden=true;justReached=before<TARGET&&correctCount()>=TARGET;feedback(justReached?'You reached the 80% target!':'Correct — keep going.',justReached?'Open your score overview to see your completion and any questions you can still improve.':result.spellingAccepted?'Your intended term was clear. A small spelling slip was accepted.':'You identified the concept in this scenario.','correct');get('next-question').textContent=justReached?'See my completion →':current===TOTAL-1?'See score overview →':'Next question →';}else feedback('Not yet — use this hint.',result.formatHint||hintFor(r,q));updateScore();save();});
get('answer').addEventListener('input',()=>{if(records[current].status!=='correct'){records[current].answer=get('answer').value;save();}});
get('hint-button').addEventListener('click',()=>{const r=records[current];r.hints++;feedback('A small starting point',hintFor(r,QUESTIONS[current]),'info');save();});
get('next-question').addEventListener('click',advance);get('skip-question').addEventListener('click',advance);get('previous-question').addEventListener('click',()=>{retryQueue=null;if(current>0)openQuestion(current-1);});get('practice-tab').addEventListener('click',()=>showView('question'));get('overview-tab').addEventListener('click',()=>showView('overview'));
function renderOverview(){const n=correctCount(),incorrect=records.filter(r=>r.status==='incorrect').length,unanswered=records.filter(r=>r.status==='unanswered').length,percent=Math.round(n/TOTAL*100);get('score-percent').textContent=percent+'%';get('score-caption').textContent=`${n} of ${TOTAL} correct`;get('score-ring').style.background=`conic-gradient(var(--green) ${n/TOTAL*360}deg, #e1e8db 0deg)`;get('correct-count').textContent=n;get('needs-work-count').textContent=incorrect;get('unanswered-count').textContent=unanswered;get('completion-banner').hidden=n<TARGET;get('overview-title').textContent=n>=TARGET?'You reached your target.':'Every retry is another step.';get('overview-message').textContent=n>=TARGET?`${percent}% correct. ${TOTAL-n?`You can still improve ${TOTAL-n} ${TOTAL-n===1?'question':'questions'}.`:'All fifteen concepts are correct.'}`:`${TARGET-n} more correct ${TARGET-n===1?'answer':'answers'} will reach the 80% target. Keep your correct answers and retry the rest.`;get('retry-questions').disabled=n===TOTAL;get('retry-questions').textContent=incorrect?'Retry the questions that need work →':'Try the remaining questions →';get('question-map').replaceChildren();QUESTIONS.forEach((q,i)=>{const r=records[i],button=document.createElement('button');button.className='question-map-item '+r.status;button.setAttribute('aria-label',`Question ${i+1}: ${q.title}. ${r.status==='correct'?'Correct':r.status==='incorrect'?'Needs another try':'Not answered yet'}`);const number=document.createElement('span');number.className='map-number';number.textContent=r.status==='correct'?'✓':String(i+1).padStart(2,'0');const title=document.createElement('span');title.className='map-label';title.textContent=q.title;const small=document.createElement('small');small.textContent=r.attempts?`${r.attempts} ${r.attempts===1?'submission':'submissions'}`:'Ready when you are';title.append(small);const status=document.createElement('span');status.className='map-status';status.textContent=r.status==='correct'?'Correct':r.status==='incorrect'?'Try again':'Not yet';button.append(number,title,status);button.addEventListener('click',()=>{retryQueue=null;openQuestion(i);});get('question-map').append(button);});}
get('retry-questions').addEventListener('click',()=>{retryQueue=records.map((r,i)=>({r,i})).filter(({r})=>r.status!=='correct').sort((a,b)=>(a.r.status==='incorrect'?0:1)-(b.r.status==='incorrect'?0:1)).map(({i})=>i);if(retryQueue.length)openQuestion(retryQueue[0]);});get('continue-practice').addEventListener('click',()=>{const pending=records.findIndex(r=>r.status!=='correct');retryQueue=null;openQuestion(pending===-1?current:pending);});
get('new-round').addEventListener('click',()=>get('reset-dialog').showModal());get('reset-dialog').addEventListener('close',()=>{if(get('reset-dialog').returnValue!=='reset')return;records=QUESTIONS.map(blankRecord);current=0;retryQueue=null;showView('question');});
let graphicsPaused=matchMedia('(prefers-reduced-motion: reduce)').matches;
function setGraphicsPaused(value){graphicsPaused=value;document.body.classList.toggle('graphics-paused',value);get('motion-toggle').textContent=value?'Resume graphics':'Pause graphics';get('motion-toggle').setAttribute('aria-pressed',String(value));}
get('motion-toggle').addEventListener('click',()=>setGraphicsPaused(!graphicsPaused));
showView(view);setGraphicsPaused(graphicsPaused);
