'use strict';
const diagram = (label,body) => `<svg viewBox="0 0 640 360" role="img" aria-label="${label}"><defs><marker id="diagram-arrow" viewBox="0 0 8 8" refX="7" refY="4" markerWidth="6" markerHeight="6" orient="auto"><path d="M0 0L8 4L0 8Z" fill="#7e9f85"/></marker></defs>${body}</svg>`;
const line = (d,extra='') => `<path class="diagram-path" d="${d}" marker-end="url(#diagram-arrow)" ${extra}/>`;
const label = (x,y,t,c='diagram-label') => `<text class="${c}" x="${x}" y="${y}">${t}</text>`;
const box = (x,y,w,h,extra='') => `<rect class="diagram-panel" x="${x}" y="${y}" width="${w}" height="${h}" rx="17" ${extra}/>`;
const cloud = (x,y) => `<g transform="translate(${x} ${y})"><path class="diagram-outline" d="M-68 22A29 29 0 0 1-50-32A45 45 0 0 1 40-37A33 33 0 0 1 66 25H-68Z"/></g>`;
const graphs = {
 room: '<div class="room-picture"><img src="assets/classroom.png" alt="A classroom temperature sensor mounted beside the whiteboard."><span class="sensor-reading">25 °C</span></div>',
 sensing: diagram('A thermometer measuring the temperature around it.',`<circle cx="320" cy="180" r="125" fill="#e0ead8"/><g class="diagram-outline"><path d="M295 218V75A25 25 0 0 1 345 75V218A46 46 0 1 1 295 218Z"/><path d="M320 215V102" stroke="#d37b4c" stroke-width="13"/><circle cx="320" cy="253" r="27" fill="#d37b4c" stroke="none"/></g><g class="diagram-pulse">${label(460,152,'27 °C','diagram-big')}${label(460,179,'A digital reading','diagram-small')}</g>${line('M363 155L405 155')}`),
 acting: diagram('A control command switches a lamp on.',`${box(55,135,125,85)}${label(117,174,'Command')}${label(117,197,'ON','diagram-small')}${line('M183 175L280 175')}<path fill="#f1d68e" opacity=".6" class="diagram-blink" d="M355 145L270 290H500L415 145Z"/><g class="diagram-outline"><path d="M332 155L350 72H420L438 155Z" fill="#fff1be"/><path d="M385 155V267M350 267H420"/><circle cx="385" cy="175" r="9" fill="#e8c75b"/></g>${label(385,318,'The lamp turns on','diagram-small')}`),
 bridge: diagram('Three device protocols enter an unnamed bridge, which sends an HTTPS message to a cloud.',`${box(30,52,126,57)}${box(30,151,126,57)}${box(30,250,126,57)}${label(93,87,'Zigbee')}${label(93,186,'BLE')}${label(93,285,'LoRa')}${line('M156 80Q215 80 270 170')}${line('M156 180L270 180')}${line('M156 280Q215 280 270 190')}<rect class="diagram-chip diagram-pulse" x="270" y="121" width="118" height="119" rx="19"/>${label(329,185,'?','diagram-big')}${line('M389 180L469 180')}${label(430,153,'HTTPS','diagram-small')}${cloud(545,180)}${label(545,250,'Internet message','diagram-small')}`),
 registry: diagram('A cloud service manages device identities, saved readings and software updates.',`${cloud(320,102)}${label(320,114,'?','diagram-big')}${line('M320 140L320 194')}${box(55,210,157,94)}${box(243,210,157,94)}${box(430,210,157,94)}${label(134,250,'Device IDs')}${label(134,278,'#0101  #0102','diagram-small')}${label(321,250,'Saved readings')}${label(321,278,'25 °C · 26 °C','diagram-small')}${label(509,250,'Updates')}${label(509,278,'Version 1 → 2','diagram-small')}`),
 decision: diagram('A local response takes 8 milliseconds; a remote cloud round trip takes 100 milliseconds; the deadline is 10 milliseconds.',`${box(40,114,118,94)}${label(99,153,'Sensor')}${label(99,178,'Hand detected','diagram-small')}${box(246,52,152,91)}${label(322,87,'Nearby node')}${label(322,117,'8 ms','diagram-big')}${box(467,114,132,94)}${label(533,153,'Robot')}${label(533,178,'STOP','diagram-small')}${line('M158 145Q190 84 246 96')}${line('M398 96Q430 84 467 145')}${cloud(321,262)}${label(321,272,'100 ms','diagram-big')}${line('M158 183Q186 268 246 268')}${line('M399 268Q430 268 467 183')}${label(321,333,'Required response: within 10 ms','diagram-small')}`),
 summary: diagram('Six individual readings become one mean, reducing the number of records sent.',`${[24,25,26,24,25,26].map((n,i)=>box(44+(i%2)*86,42+Math.floor(i/2)*88,70,63)+label(79+(i%2)*86,80+Math.floor(i/2)*88,n+'°')).join('')}${line('M224 173L371 173')}${label(292,152,'Combine','diagram-small')}${box(395,99,195,155)}${label(492,160,'25.0 °C','diagram-big')}${label(492,192,'One mean','diagram-small')}${label(492,227,'1 record / second','diagram-small')}${label(128,325,'Many raw readings','diagram-small')}`),
 invalid: diagram('Three plausible temperature readings and one impossible reading of twenty thousand degrees Celsius.',`${[25,26,20000,24].map((v,i)=>box(70+(i%2)*280,63+Math.floor(i/2)*144,220,112,v===20000?'style="fill:#fae8da;stroke:#d3906c"':'')+label(180+(i%2)*280,123+Math.floor(i/2)*144,v.toLocaleString()+' °C','diagram-big')+label(180+(i%2)*280,153+Math.floor(i/2)*144,v===20000?'Outside the sensor range':'Room reading','diagram-small')).join('')}`),
 order: diagram('Shuffled timestamped records are put into chronological order.',`${['09:03','09:01','09:02'].map((v,i)=>box(45,57+i*88,172,62)+label(131,95+i*88,v)).join('')}${line('M223 171L405 171')}${['09:01','09:02','09:03'].map((v,i)=>box(417,57+i*88,172,62)+label(503,95+i*88,v)).join('')}${label(132,338,'Before','diagram-small')}${label(503,338,'After','diagram-small')}`),
 archive: diagram('The number of stored records increases over ten years.',`<path d="M85 285H560M85 285V55" stroke="#b4c9ac" stroke-width="2" fill="none"/>${[42,83,125,185,231].map((h,i)=>`<rect x="${119+i*86}" y="${285-h}" width="52" height="${h}" rx="6" fill="${i===4?'#276b52':'#9abc9b'}" class="diagram-rise"/>`).join('')}${label(145,315,'Year 1','diagram-small')}${label(489,315,'Year 10','diagram-small')}${label(318,40,'Stored entry records','diagram-label')}`),
 formats: diagram('Heart-rate numbers, audio and video combine in one system.',`${box(35,91,160,160)}${box(239,91,160,160)}${box(443,91,160,160)}<path d="M66 156H90L103 125L124 184L141 148H165" class="diagram-outline" fill="none"/>${label(115,217,'72 bpm')}${label(115,281,'Numbers','diagram-small')}<g stroke="#7fa9b0" stroke-width="7" stroke-linecap="round">${[18,43,63,32,50,20].map((h,i)=>`<path d="M${273+i*18} ${161-h/2}V${161+h/2}"/>`).join('')}</g>${label(319,217,'Sleep audio')}${label(319,281,'Sound','diagram-small')}<rect class="diagram-outline" x="481" y="123" width="83" height="63" rx="8"/><path d="M513 138L539 155L513 172Z" fill="#276b52"/>${label(523,217,'Workout video')}${label(523,281,'Images','diagram-small')}`),
 arrival: diagram('A gas detector sends an alert, but the alert arrives forty-five seconds late.',`${box(35,123,137,107)}${label(103,165,'Gas sensor')}${label(103,192,'Alert sent','diagram-small')}${line('M177 178L462 178')}<g class="diagram-pulse"><circle cx="225" cy="178" r="8" fill="#276b52"/><circle cx="290" cy="178" r="8" fill="#7aa484"/><circle cx="355" cy="178" r="8" fill="#b2c6aa"/></g>${box(467,123,137,107)}${label(535,165,'Alarm')}${label(535,192,'Arrives late','diagram-small')}${label(320,95,'45 seconds','diagram-big')}${label(320,272,'A warning needs a timely response','diagram-small')}`),
 bias: diagram('A sensor beside an air-conditioning vent reads twenty-two degrees while the rest of the room is twenty-eight degrees.',`<rect class="diagram-chip" x="53" y="52" width="535" height="252" rx="20"/><rect class="diagram-outline" x="76" y="75" width="114" height="46" rx="8"/>${label(133,103,'Aircon vent','diagram-small')}<path d="M99 124Q81 158 105 174M126 124Q107 165 134 190M154 124Q136 164 161 180" class="diagram-path" stroke="#7fa9b0"/>${box(103,189,158,80)}${label(182,225,'22 °C','diagram-big')}${label(182,250,'Beside the vent','diagram-small')}${box(362,189,179,80)}${label(451,225,'28 °C','diagram-big')}${label(451,250,'Rest of the room','diagram-small')}${label(320,338,'Both readings are plausible','diagram-small')}`),
 unused: diagram('A large data store exists, but nobody uses it to make a decision.',`<g class="diagram-outline"><ellipse cx="170" cy="95" rx="88" ry="29"/><path d="M82 95V245C82 284 258 284 258 245V95M82 147C82 186 258 186 258 147M82 199C82 238 258 238 258 199"/></g>${label(170,319,'Terabytes collected','diagram-small')}${line('M274 177L393 177')}<g><rect class="diagram-outline" x="410" y="90" width="166" height="167" rx="15"/><path d="M436 216V126M436 216H552" stroke="#c3d1bb" stroke-width="2"/>${label(493,175,'?','diagram-big')}</g>${label(493,319,'No decision or action','diagram-small')}`),
 battery: diagram('A small wearable uses a compact battery and lasts ten days.',`<g class="diagram-outline"><rect x="245" y="22" width="149" height="316" rx="46" fill="#bdcdb5"/><rect x="218" y="104" width="205" height="151" rx="34" fill="#fffefa"/></g><rect x="269" y="132" width="100" height="49" rx="7" fill="#e1ead9" stroke="#638a72" stroke-width="2"/><rect x="280" y="144" width="67" height="26" rx="3" fill="#276b52" class="diagram-blink"/><path d="M371 146H379V166H371" fill="#638a72"/>${label(320,217,'10 days','diagram-big')}${label(320,242,'between charges','diagram-small')}`)
};
const QUESTIONS=[
 {id:'device',title:'A reading from the classroom',tag:'CLASSROOM',graphic:'room',caption:'A connected temperature sensor reports 25 °C from the classroom.',prompt:'Which of the three IoT ecosystem building blocks does this sensor belong to?',answers:['device','devices','iot device','connected device','node','thing'],hints:['Think about the part of the ecosystem that touches the physical world.','It collects measurements before another component carries or stores them.','Name the ecosystem building block, rather than a particular sensor model.']},
 {id:'sense',title:'The room becomes a number',tag:'DEVICE CAPABILITIES',graphic:'sensing',caption:'The thermometer turns a physical temperature into a digital reading.',prompt:'Which device capability measures the surroundings?',answers:['sense','sensing'],hints:['Think about how a device discovers what is happening around it.','This capability produces a measurement; it does not change the room.','Use the capability’s name or its “-ing” form.']},
 {id:'act',title:'The light responds',tag:'DEVICE CAPABILITIES',graphic:'acting',caption:'A command causes the connected lamp to turn on.',prompt:'Which device capability changes the physical world in response to a command?',answers:['act','acting','actuation'],hints:['The device is doing something back to its surroundings.','Compare taking a measurement with switching an appliance.','Name the capability responsible for the physical response.']},
 {id:'gateway',title:'Different messages, one bridge',tag:'ECOSYSTEM',graphic:'bridge',caption:'A box accepts Zigbee, BLE and LoRa messages and forwards an internet message.',prompt:'Which IoT ecosystem component translates these device protocols and forwards the readings?',answers:['gateway','gateways','iot gateway','smart hub','hub'],hints:['Think about the component between devices and internet services.','This component can also buffer readings when a connection drops.','Name the bridge component rather than the cloud service.']},
 {id:'platform',title:'Managing a whole fleet',tag:'ECOSYSTEM',graphic:'registry',caption:'A cloud service keeps device identities, saves readings and supports updates.',prompt:'Which IoT ecosystem component manages devices and stores their data at this scale?',answers:['platform','platforms','iot platform','cloud platform','cloud service','cloud services'],hints:['Think about the component that manages data from many connected things.','It can maintain a device registry and support analytics or dashboards.','Name the management component, rather than the device producing a reading.']},
 {id:'edge',title:'A stop cannot wait',tag:'PROCESSING LOCATION',graphic:'decision',caption:'A nearby response takes 8 ms. A remote round trip takes 100 ms. The deadline is 10 ms. These are example values.',prompt:'Which computing approach should make this urgent stop decision close to the sensor?',answers:['edge','edge computing','local processing','local computing','on device processing','on device computing','on site processing'],hints:['Compare the two response times with the deadline.','The decision needs to happen without depending on a distant round trip.','Name the computing approach where processing stays close to the data source.']},
 {id:'aggregation',title:'Many readings become one summary',tag:'DATA PROCESSING',graphic:'summary',caption:'Several measurements combine into one mean before transmission.',prompt:'Which processing step combines multiple readings into a smaller summary?',answers:['aggregation','data aggregation','aggregating','averaging','average','batch averaging'],hints:['The problem is the number of records being sent.','This step can use a mean, sum, minimum or maximum.','Name the combining step rather than the step that checks for impossible values.']},
 {id:'validation',title:'One reading does not belong',tag:'DATA PROCESSING',graphic:'invalid',caption:'The sensor reports 20,000 °C alongside ordinary room readings.',prompt:'Which processing step checks whether a reading is within the sensor’s allowed range?',answers:['validation','data validation','validating','range check','range checking','checking the range','range validation'],hints:['The problem is an impossible measurement, rather than too many records.','Compare the reading with what the sensor is physically able to measure.','Name the step that checks whether a value is acceptable.']},
 {id:'sorting',title:'Restore the sequence',tag:'DATA PROCESSING',graphic:'order',caption:'The records have the same values, but their timestamp order changes.',prompt:'Which processing step puts these readings into time order?',answers:['sorting','sort','ordering','time ordering','chronological sorting','sorting by timestamp'],hints:['The values stay the same. Their positions change.','Look at the timestamps before and after the operation.','Name the operation that puts records into a chosen sequence.']},
 {id:'volume',title:'Ten years of carpark records',tag:'BIG DATA',graphic:'archive',caption:'The store keeps growing as entry records accumulate over years.',prompt:'Which V describes the amount of data that has accumulated?',answers:['volume','data volume'],hints:['Focus on the total amount stored, rather than how fast new records arrive.','More devices or a longer collection period can increase this property.','Choose the V concerned with the scale of the data store.']},
 {id:'variety',title:'Numbers, sound and moving images',tag:'BIG DATA',graphic:'formats',caption:'A health app combines heart-rate numbers, sleep audio and workout video.',prompt:'Which V describes these different forms of data?',answers:['variety','data variety'],hints:['The issue is the mix of data forms.','A number, an audio clip and an image need different ways of representing their content.','Choose the V about different types and formats rather than their total amount.']},
 {id:'velocity',title:'The warning arrives too late',tag:'BIG DATA',graphic:'arrival',caption:'The alert takes 45 seconds to reach the alarm in this example.',prompt:'Which V concerns the speed of arriving data and timely processing?',answers:['velocity','data velocity'],hints:['Focus on timing, rather than the number of years stored.','An urgent event needs the system to keep up with incoming readings.','Choose the V about how fast data flows and needs processing.']},
 {id:'veracity',title:'Plausible readings, misleading placement',tag:'BIG DATA',graphic:'bias',caption:'A sensor beside the aircon vent reads lower than the rest of the room.',prompt:'Which V is affected when sensor placement makes the data unrepresentative?',answers:['veracity','data veracity'],hints:['The reading is possible, but it may not represent the whole room.','Ask whether the collected data is trustworthy for this decision.','Choose the V about uncertainty and the reliability of the evidence.']},
 {id:'value',title:'Collected, but never used',tag:'BIG DATA',graphic:'unused',caption:'A company collects a large store of readings but makes no decision from it.',prompt:'Which V is missing when the data supports no useful insight, decision or action?',answers:['value','data value'],hints:['Having lots of data does not automatically make it useful.','Think about the outcome the organisation gets from its data.','Choose the V about usefulness, rather than the size or speed of the data.']},
 {id:'energy',title:'A tiny device has a long day',tag:'CONSTRAINED DEVICES',graphic:'battery',caption:'The wearable lasts ten days between charges in this example.',prompt:'Which limited resource must a battery-powered IoT device conserve to keep running?',answers:['energy','power','battery','battery power','battery energy','battery life','electricity','electrical energy'],hints:['Think about what runs out between charges.','The device consumes this resource whenever it senses, processes or communicates.','Name the resource supplied by the battery, rather than processing speed or memory.']}
];
