'use strict';
const $ = id => document.getElementById(id);
const all = selector => [...document.querySelectorAll(selector)];
const reducedMotion = matchMedia('(prefers-reduced-motion: reduce)').matches;
const state = {view:'classroom', device:'temperature', lamp:false, lights:false, cooling:false, paused:reducedMotion, clock:0, tasks:[], buffer:0, v:'volume', queue:0, processed:0, vSettings:{rooms:10, days:7, rate:20, bias:0, decision:false, formats:['numbers','events']}, quizIndex:0, score:0, answered:false, race:null};
const devices = {
 temperature:{name:'Temperature sensor',description:'Measures the classroom’s temperature and shares a digital reading.',unit:'°C',qualities:[['SENSE','Measures ambient temperature.'],['CONNECT','Sends readings over Zigbee.'],['PROCESS','Converts its measurement to a digital value.']]},
 occupancy:{name:'Occupancy sensor',description:'Detects presence so local rules can respond when the room is in use. The slider represents a simulated presence input.',unit:'presence',qualities:[['SENSE','Detects whether someone is present.'],['CONNECT','Shares a presence event over BLE.'],['PROCESS','Filters brief changes before reporting.']]},
 aircon:{name:'Connected air conditioner',description:'Receives a command and changes the physical environment by switching cooling on or off.',unit:'cooling',qualities:[['ACT','Controls the cooling system.'],['CONNECT','Receives a local control command.'],['PROCESS','Applies the requested operating mode.']]},
 plug:{name:'Smart plug & lamp',description:'An illustrative smart plug measures current and switches the connected lamp. Capabilities vary between products.',unit:'A',qualities:[['SENSE','Measures electrical current.'],['ACT','Switches the lamp on or off.'],['CONNECT','Uses Wi-Fi through a router.'],['PROCESS','Applies its on/off control logic.']]}
};
function schedule(delay,fn,tag){state.tasks.push({due:state.clock+delay,fn,tag});}
function cancel(tag){state.tasks=state.tasks.filter(t=>t.tag!==tag);}
function setView(view, updateHash=true){if(!$(view)?.classList.contains('view'))view='classroom';state.view=view;all('.view').forEach(el=>{el.hidden=el.id!==view;el.classList.toggle('active',el.id===view);});all('[data-view]').forEach(b=>{const active=b.dataset.view===view;b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});if(updateHash)history.replaceState(null,'','#'+view);}
all('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));
addEventListener('hashchange',()=>setView(location.hash.slice(1),false));
function pauseMotion(paused){state.paused=paused;document.body.classList.toggle('paused',paused);$('pause').textContent=paused?'Resume motion':'Pause motion';$('pause').setAttribute('aria-pressed',String(paused));all('svg').forEach(svg=>{if(svg.pauseAnimations){if(paused)svg.pauseAnimations();else svg.unpauseAnimations();}});}
$('pause').addEventListener('click',()=>pauseMotion(!state.paused));
function roomUpdate(){const n=+$('occupancy').value,t=+$('temperature').value,auto=$('automation').checked;if(auto){state.lights=n>0;state.cooling=n>0&&t>27;}else{state.lights=false;state.cooling=false;}
 $('occupancy-out').textContent=n;$('temperature-out').textContent=t+' °C';$('lights-status').textContent=state.lights?'On':'Off';$('cooling-status').textContent=state.cooling?'On':'Off';$('lamp-toggle').textContent=state.lamp?'Turn lamp off':'Turn lamp on';$('room').classList.toggle('lit',state.lamp);$('room').classList.toggle('connected',$('connections').checked);$('room').classList.toggle('lights-on',state.lights);$('room').classList.toggle('cooling-on',state.cooling);
 const places=[[39,49],[52,49],[66,49],[52,63],[68,63],[27,67]];if($('people').children.length!==n)$('people').innerHTML=places.slice(0,n).map(([x,y],i)=>`<i class="person" style="left:${x}%;top:${y}%;background:${i%2?'#8b9b76':'#397f68'}"></i>`).join('');
 $('room-caption').textContent=n===0?'An empty room. Automatic lights and cooling stay off.':!auto?'People are present. Automatic lighting and cooling rules are disabled.':state.cooling?'People are present. Lights and cooling are on.':'People are present. Lights are on; cooling stays off.';
 const d=devices[state.device];$('device-name').textContent=d.name;$('device-description').textContent=d.description;$('device-unit').textContent=d.unit;$('device-reading').textContent=state.device==='temperature'?t:state.device==='occupancy'?(n>0?'Yes':'No'):state.device==='aircon'?(state.cooling?'On':'Off'):(state.lamp?'0.05':'0.00');$('device-qualities').innerHTML=d.qualities.map(([name,desc])=>`<div class="quality"><strong>${name}</strong><span>${desc}</span></div>`).join('');all('[data-device]').forEach(b=>{b.classList.toggle('selected',b.dataset.device===state.device);b.setAttribute('aria-pressed',String(b.dataset.device===state.device));});
}
all('[data-device]').forEach(b=>b.addEventListener('click',()=>{state.device=b.dataset.device;roomUpdate();}));
['occupancy','temperature','automation','connections'].forEach(id=>$(id).addEventListener('input',()=>{cancel('story');$('story').disabled=false;$('story-note').textContent='Your changes drive the classroom rules.';roomUpdate();}));
$('lamp-toggle').addEventListener('click',()=>{state.lamp=!state.lamp;roomUpdate();});
$('story').addEventListener('click',()=>{cancel('story');pauseMotion(false);$('story').disabled=true;$('automation').checked=true;$('occupancy').value=0;$('temperature').value=25;state.device='occupancy';roomUpdate();$('story-note').textContent='1 / 4 · The classroom starts empty.';schedule(1800,()=>{$('occupancy').value=3;roomUpdate();$('story-note').textContent='2 / 4 · Presence is detected. The local rule switches the lights on.';},'story');schedule(4000,()=>{$('temperature').value=30;state.device='temperature';roomUpdate();$('story-note').textContent='3 / 4 · The temperature reading rises to 30 °C.';},'story');schedule(6300,()=>{state.device='aircon';$('connections').checked=true;roomUpdate();$('story-note').textContent='4 / 4 · The room is occupied and above 27 °C. A command turns cooling on.';$('story').disabled=false;},'story');});
function networkLog(text){$('network-log').textContent=text;}
function sendReading(){const value=+$('temperature').value;const payload=`{ device: "temp-01", value: ${value}, unit: "°C", timestamp: "${new Date().toISOString().slice(11,19)}" }`;if(!$('internet').checked){state.buffer++;$('buffer-count').textContent=state.buffer;networkLog('Internet unavailable. Gateway stores reading '+state.buffer+' locally: '+payload);}else{networkLog('Device → gateway: Zigbee reading. Gateway → platform: HTTPS message '+payload+' Platform stores it for the dashboard.');}}
$('send-reading').addEventListener('click',sendReading);
// Network indicators and buffering work independently of the classroom’s local rules.
$('internet').addEventListener('change',()=>{const online=$('internet').checked;document.querySelector('.network-scene').classList.toggle('offline',!online);$('network-status').textContent=online?'Internet connected':'Internet unavailable';if(online){networkLog(state.buffer?`Connection restored. Gateway uploads ${state.buffer} buffered message${state.buffer===1?'':'s'} to the platform.`:'Connection restored. New readings can reach the platform.');state.buffer=0;$('buffer-count').textContent='0';}else{networkLog('Internet disconnected. Local classroom rules continue. Send readings to see gateway buffering.');}});
$('send-command').addEventListener('click',()=>{if(!$('internet').checked){networkLog('The cloud command cannot reach the classroom while the internet is unavailable. Local rules can still operate.');return;}document.querySelector('.network-scene').classList.add('commanding');state.cooling=true;$('cooling-status').textContent='On';if(state.device==='aircon')$('device-reading').textContent='On';networkLog('Teacher app → platform → gateway → aircon: cooling ON. A manual override acts now; changing the room inputs reapplies the classroom rule.');cancel('command');schedule(3000,()=>document.querySelector('.network-scene').classList.remove('commanding'),'command');});
const readings=[{time:'09:00:03',value:26},{time:'09:00:01',value:25},{time:'09:00:04',value:20000},{time:'09:00:02',value:24},{time:'09:00:06',value:27},{time:'09:00:05',value:25}];
function datum(r,flag=false){return `<div class="datum ${flag?'invalid':''}"><small>${r.time}</small><strong>${r.value.toLocaleString()} °C${flag?' · flagged':''}</strong></div>`;}
function processUpdate(){const validate=$('validate').checked,sort=$('sort').checked,aggregate=$('aggregate').checked;let output=readings.filter(r=>!validate||(r.value>=-10&&r.value<=60));if(sort)output.sort((a,b)=>a.time.localeCompare(b.time));const mean=output.reduce((s,r)=>s+r.value,0)/output.length;$('raw-readings').innerHTML=readings.map(r=>datum(r,validate&&(r.value< -10||r.value>60))).join('');$('processed-readings').innerHTML=aggregate?`<div class="aggregate-result"><strong>${mean.toFixed(1)} °C</strong><p>One batch mean from ${output.length} readings</p><small>Raw readings can remain stored locally.</small></div>`:output.map(r=>datum(r)).join('');$('invalid-count').textContent=validate?'1':'0';$('output-count').textContent=aggregate?'1':output.length;$('mean-reading').textContent=mean.toFixed(1)+' °C';$('process-caption').textContent=[validate?'Remove the impossible reading.':'',sort?'Order records by time.':'',aggregate?'Send one batch mean.':''].filter(Boolean).join(' ')||'Readings pass through unchanged.';}
['validate','sort','aggregate'].forEach(id=>$(id).addEventListener('change',processUpdate));$('process-reset').addEventListener('click',()=>{['validate','sort','aggregate'].forEach(id=>$(id).checked=false);processUpdate();});
$('latency').addEventListener('input',()=>$('latency-out').textContent=$('latency').value+' ms');
const edgePaths={};
function pathGeometry(d){const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',d);return {path,length:path.getTotalLength()};}
edgePaths.local=pathGeometry('M200 155 L280 155 L440 155 L520 155');
edgePaths.outbound=pathGeometry('M120 205 L120 355 L280 355 L440 355 L720 355 L840 355 L900 355');
edgePaths.return=pathGeometry('M900 385 L840 385 L720 385 L440 385 L360 410 L360 470 L690 470 L690 240 L600 240 L600 205');
edgePaths.blocked=pathGeometry('M120 205 L120 355 L280 355 L440 355 L570 355');
function placeSignal(id,geometry,fraction){const p=geometry.path.getPointAtLength(geometry.length*Math.min(1,Math.max(0,fraction)));$(id).setAttribute('cx',p.x);$(id).setAttribute('cy',p.y);$(id).setAttribute('visibility','visible');}
function resetEdgeDiagram(){['edge-dot','cloud-dot'].forEach(id=>$(id).setAttribute('visibility','hidden'));$('edge-network').classList.remove('edge-stopped','cloud-arrived','edge-offline');$('robot-state').textContent='WAITING FOR A STOP';$('internet-map-state').textContent=$('edge-internet').checked?'CONNECTED':'OFFLINE';$('broken-link').setAttribute('visibility',$('edge-internet').checked?'hidden':'visible');$('edge-map-caption').textContent='One sensor. Two possible places to decide.';all('.edge-node.active-node').forEach(el=>el.classList.remove('active-node'));}
function highlightEdgeNodes(ids){all('.edge-node').forEach(el=>el.classList.toggle('active-node',ids.includes(el.id)));}
function startEdgeDiagram(mode='compare',teaching=false){pauseMotion(false);resetEdgeDiagram();const online=$('edge-internet').checked,latency=+$('latency').value;state.race={start:state.clock,latency,online,mode,teaching,edgeDuration:teaching?2400:320,cloudDuration:teaching?5000:(latency+20)*40,offlineDuration:teaching?1800:900};$('edge-result').textContent=mode==='cloud'?'8 ms · local example':'Detecting…';$('cloud-result').textContent=mode==='edge'?'Not needed for this route':'Waiting for response…';$('cloud-result').classList.remove('late');$('edge-run').disabled=true;$('edge-note').textContent=teaching?'Animation is paced for learning. Time labels are illustrative response values, not the duration of the animation.':'Animation slows both routes by 40×. Cloud response = network round trip + 20 ms processing. Local response = 8 ms. Timing values are illustrative.';raceUpdate();}
function raceUpdate(){if(!state.race)return;const r=state.race,elapsed=state.clock-r.start,hasEdge=r.mode!=='cloud',hasCloud=r.mode!=='edge',ep=Math.min(1,elapsed/r.edgeDuration),cp=Math.min(1,elapsed/(r.online?r.cloudDuration:r.offlineDuration)),outEnd=r.teaching?.5:r.latency/2/(r.latency+20),decisionEnd=r.teaching?.62:outEnd+20/(r.latency+20);let caption='',focus=[];
 if(hasEdge){placeSignal('edge-dot',edgePaths.local,ep);if(ep<.35){caption='The hand sensor sends a detection to the nearby edge controller.';focus=['sensor-node'];}else if(ep<.75){caption='The edge controller decides inside the factory.';focus=['edge-controller-node'];}else{caption='The local STOP command reaches the robot.';focus=['robot-node'];}if(ep===1){$('edge-result').textContent='8 ms · deadline met';$('edge-network').classList.add('edge-stopped');$('robot-state').textContent='STOPPED LOCALLY';$('edge-dot').setAttribute('visibility','hidden');}}
 if(hasCloud){if(!r.online){placeSignal('cloud-dot',edgePaths.blocked,cp);$('edge-network').classList.add('edge-offline');$('broken-link').setAttribute('visibility','visible');$('internet-map-state').textContent='OFFLINE';caption=cp===1?'The internet link is down. The reading cannot reach the cloud.':'The reading reaches the gateway, but the internet link is unavailable.';focus=cp<.45?['sensor-node']:['edge-gateway-node'];if(cp===1){$('cloud-result').textContent='Offline · no cloud response';$('cloud-result').classList.add('late');if(hasEdge&&ep===1)caption='The local STOP arrived. The cloud route is blocked at the internet link.';}}
 else if(cp<outEnd){placeSignal('cloud-dot',edgePaths.outbound,cp/outEnd);if(cp/outEnd<.26){caption='The sensor reading travels to the factory gateway.';focus=['sensor-node','edge-gateway-node'];}else if(cp/outEnd<.76){caption='The gateway sends the reading across the internet.';focus=['edge-gateway-node','internet-node'];}else{caption='The reading arrives at the remote cloud service.';focus=['remote-cloud-node'];}}
 else if(cp<decisionEnd){placeSignal('cloud-dot',edgePaths.outbound,1);caption='The cloud processes the reading and decides to stop the robot.';focus=['remote-cloud-node'];}
 else{placeSignal('cloud-dot',edgePaths.return,(cp-decisionEnd)/(1-decisionEnd));caption='The STOP command returns through the internet and gateway to the robot.';focus=cp<.82?['internet-node','edge-gateway-node']:['robot-node'];if(cp===1){$('cloud-result').textContent=(r.latency+20)+' ms · deadline missed';$('cloud-result').classList.add('late');$('cloud-dot').setAttribute('visibility','hidden');$('edge-network').classList.add('cloud-arrived');if(!hasEdge)$('robot-state').textContent='CLOUD STOP ARRIVED LATE';caption=hasEdge?'The robot already stopped locally at 8 ms. The cloud command arrived at '+(r.latency+20)+' ms.':'The cloud STOP arrives at '+(r.latency+20)+' ms, beyond the 10 ms deadline.';}}}
 $('edge-map-caption').textContent=caption;highlightEdgeNodes(focus);if((!hasEdge||ep===1)&&(!hasCloud||cp===1)){state.race=null;$('edge-run').disabled=false;}}
$('edge-run').addEventListener('click',()=>startEdgeDiagram());
$('edge-internet').addEventListener('change',()=>{if(!state.race)resetEdgeDiagram();});
const vCopy={volume:['HOW MUCH ACCUMULATES?','Volume','Repeated readings build up across classrooms and over time. Add rooms or days to see the number of stored records grow.'],variety:['WHAT FORMS DOES IT TAKE?','Variety','IoT systems can combine numeric records, events, images and audio. Each form needs appropriate storage and processing.'],velocity:['HOW FAST DOES IT ARRIVE?','Velocity','Arrival speed is different from accumulated size. When data arrives faster than the processor can handle it, a backlog grows.'],veracity:['HOW MUCH CAN YOU TRUST IT?','Veracity','Sensors beside an aircon vent can report cooler temperatures than the rest of the room. Even plausible readings can produce a biased result.'],value:['WHAT DECISION DOES IT SUPPORT?','Value','Data becomes useful when it supports an action. Connect occupancy and temperature readings to a cooling rule and compare its behaviour.']};
function rangeControl(id,label,min,max,value,unit=''){return `<label for="${id}">${label}<output id="${id}-out">${value}${unit}</output><input id="${id}" type="range" min="${min}" max="${max}" value="${value}"></label>`;}
function selectV(v){state.v=v;all('[data-v]').forEach(b=>{b.classList.toggle('active',b.dataset.v===v);b.setAttribute('aria-pressed',String(b.dataset.v===v));});const [question,title,description]=vCopy[v];$('v-question').textContent=question;$('v-title').textContent=title;$('v-description').textContent=description;const s=state.vSettings;
 if(v==='volume')$('v-controls').innerHTML=rangeControl('v-rooms','Classrooms',1,100,s.rooms)+rangeControl('v-days','Days of collection',1,365,s.days);
 if(v==='variety')$('v-controls').innerHTML=[['numbers','Temperature numbers'],['events','Occupancy events'],['images','Camera images'],['audio','Audio clips']].map(([key,label])=>`<label><input data-format="${key}" type="checkbox" ${s.formats.includes(key)?'checked':''}> ${label}</label>`).join('');
 if(v==='velocity')$('v-controls').innerHTML=rangeControl('v-rate','Incoming readings / second',1,100,s.rate)+'<button id="queue-reset" class="quiet">Clear the queue</button>';
 if(v==='veracity')$('v-controls').innerHTML=rangeControl('v-bias','Sensors beside the aircon vent',0,5,s.bias,' of 5');
 if(v==='value')$('v-controls').innerHTML='<label><input id="v-decision" type="checkbox" '+(s.decision?'checked':'')+'> Use occupancy to control cooling</label>';
 all('#v-controls input').forEach(input=>input.addEventListener('input',()=>{if(input.id==='v-rooms')s.rooms=+input.value;if(input.id==='v-days')s.days=+input.value;if(input.id==='v-rate')s.rate=+input.value;if(input.id==='v-bias')s.bias=+input.value;if(input.id==='v-decision')s.decision=input.checked;if(input.dataset.format)s.formats=input.checked?[...s.formats,input.dataset.format]:s.formats.filter(f=>f!==input.dataset.format);renderV();}));if($('queue-reset'))$('queue-reset').addEventListener('click',()=>{state.queue=0;state.processed=0;renderV();});renderV();}
all('[data-v]').forEach(b=>b.addEventListener('click',()=>selectV(b.dataset.v)));
function renderV(){const s=state.vSettings,v=state.v;
 if(v==='volume'){const records=s.rooms*s.days*4*1440,bytes=records*100,fill=Math.max(1,Math.ceil(records/(100*365*4*1440)*50));$('v-stage').innerHTML='<div class="v-stage-title">A GROWING DATA STORE</div><div class="storage">'+Array.from({length:50},(_,i)=>`<i class="${i<fill?'filled':''}"></i>`).join('')+'</div><div class="scale-label">Illustrative scale: up to 210.24 million records</div>';$('v-metric').textContent=records.toLocaleString();$('v-metric-label').textContent='stored readings';$('v-note').textContent=`Assumption: four sensors per room, one reading per minute, 100 bytes per record. About ${(bytes/1e9).toFixed(2)} GB before storage overhead. Whether it is “big” depends on your tools.`;$('v-rooms-out').textContent=s.rooms;$('v-days-out').textContent=s.days;}
 if(v==='variety'){const formats={numbers:['25°','Temperature record','Structured · device ID, time and number'],events:['◎','Occupancy event','Structured · presence flag and timestamp'],images:['▧','Camera image','Image pixels with associated metadata'],audio:['≋','Audio clip','Waveform with associated metadata']};$('v-stage').innerHTML='<div class="v-stage-title">DIFFERENT FORMS, ONE SYSTEM</div><div class="format-stream">'+s.formats.map(f=>{const d=formats[f];return `<div class="format-item"><div class="format-icon">${d[0]}</div><div><strong>${d[1]}</strong><small>${d[2]}</small></div></div>`;}).join('')+(s.formats.length?'':'<p>Select a data form to add it to the system.</p>')+'</div>';$('v-metric').textContent=s.formats.length;$('v-metric-label').textContent='data forms selected';$('v-note').textContent='Images and audio are unstructured content, but can include structured metadata. Adding a camera or microphone also raises privacy and consent questions.';}
 if(v==='velocity'){if(!$('queue-fill'))$('v-stage').innerHTML='<div class="v-stage-title">LIVE STREAM & PROCESSING QUEUE</div><div class="stream-vis"><div class="stream-source">Classroom<br>sensors</div><div class="stream-lane">'+Array.from({length:8},(_,i)=>`<i style="animation-delay:${-i/4}s"></i>`).join('')+'</div><div class="stream-processor">Processor<br>30 / sec</div></div><div class="queue-track"><div id="queue-fill"></div></div><div class="scale-label" id="queue-label"></div>';$('queue-fill').style.width=Math.min(100,state.queue/5)+'%';$('queue-label').textContent=`Backlog: ${state.queue.toLocaleString()} readings · Processed: ${state.processed.toLocaleString()}`;all('.stream-lane i').forEach(i=>i.style.animationDuration=(60/s.rate)+'s');$('v-metric').textContent=s.rate+' / sec';$('v-metric-label').textContent='incoming readings';$('v-note').textContent='Processor capacity is 30 readings per second. Above 30, the queue grows; below 30, an existing queue drains. The queue advances only while this experiment is visible and motion is running.';$('v-rate-out').textContent=s.rate;}
 if(v==='veracity'){const mean=((5-s.bias)*28+s.bias*22)/5;$('v-stage').innerHTML=`<div class="v-stage-title">SENSOR PLACEMENT CHANGES THE RESULT</div><div class="bias-bars"><div class="bias-bar"><span>Room reference</span><i style="width:93.3%"></i><strong>28 °C</strong></div><div class="bias-bar"><span>Reported mean</span><i style="width:${mean/30*100}%"></i><strong>${mean.toFixed(1)} °C</strong></div></div><p class="scale-label">${5-s.bias} sensors read 28 °C in the room.<br>${s.bias} sensors read 22 °C beside the vent.</p>`;$('v-metric').textContent=(28-mean).toFixed(1)+' °C';$('v-metric-label').textContent='underestimate of the room reference';$('v-note').textContent='All five readings fall within the valid sensor range. A range check alone cannot detect this placement bias. Compare representative locations and calibrate sensors.';$('v-bias-out').textContent=s.bias+' of 5';}
 if(v==='value'){const savings=s.decision?4:0;$('v-stage').innerHTML=`<div class="v-stage-title">A DECISION THAT USES THE DATA</div><div class="decision-vis"><div><strong>30 °C</strong>Room empty<br>after class</div><span class="flow-arrow">→</span><div><strong>${s.decision?'Off':'On'}</strong>Cooling<br>${s.decision?'uses occupancy':'runs on schedule'}</div></div><p class="scale-label">Example day: eight scheduled cooling hours, four occupied hours.</p>`;$('v-metric').textContent=savings+' hours';$('v-metric-label').textContent='of unnecessary cooling avoided in this example';$('v-note').textContent='Illustrative assumptions: the room is hot throughout the scheduled day, and cooling is unnecessary during four empty hours. This is operating time avoided, not a measured energy saving.';}
}
const questions=[
 {q:'A soil-moisture probe sends a reading every ten minutes. Which ecosystem component is it?',options:['Device','Gateway','Platform'],answer:0,why:'A device senses the physical world and produces a reading.'},
 {q:'A box converts Zigbee traffic to HTTPS and buffers data when the internet drops. What is it?',options:['Device','Gateway','Platform'],answer:1,why:'Protocol translation and buffering are gateway functions.'},
 {q:'A cloud service keeps a registry of 50,000 devices and pushes firmware updates. What is it?',options:['Device','Gateway','Platform'],answer:2,why:'A platform manages device identities and supports device updates at scale.'},
 {q:'Ten years of carpark records make queries take hours. Which V is the main challenge?',options:['Volume','Variety','Velocity','Veracity','Value'],answer:0,why:'The accumulated amount of historical data creates a volume challenge.'},
 {q:'A health app combines heart-rate numbers, audio and workout video. Which V does this illustrate?',options:['Volume','Variety','Velocity','Veracity','Value'],answer:1,why:'Different forms of data create a variety challenge.'},
 {q:'A gas-leak alert arrives 45 seconds late. Which V is the main challenge?',options:['Volume','Variety','Velocity','Veracity','Value'],answer:2,why:'The system needs to process arriving data quickly enough to support a timely response.'},
 {q:'Half the temperature sensors sit beside aircon vents and skew the result. Which V is the problem?',options:['Volume','Variety','Velocity','Veracity','Value'],answer:3,why:'Sensor placement undermines how representative and trustworthy the data is.'},
 {q:'A company collects terabytes of sensor data, but nobody uses it. Which V is missing?',options:['Volume','Variety','Velocity','Veracity','Value'],answer:4,why:'The data has little value until it supports a useful insight, decision or action.'}
];
function quizRender(){state.answered=false;$('quiz-next').hidden=true;$('quiz-feedback').textContent='';$('quiz-progress').textContent=`QUESTION ${state.quizIndex+1} OF ${questions.length}`;$('quiz-score').textContent=`${state.score} correct`;const q=questions[state.quizIndex];$('quiz-question').textContent=q.q;$('quiz-options').innerHTML=q.options.map((o,i)=>`<button data-answer="${i}">${o}</button>`).join('');all('[data-answer]').forEach(b=>b.addEventListener('click',()=>{if(state.answered)return;state.answered=true;const correct=+b.dataset.answer===q.answer;if(correct)state.score++;all('[data-answer]').forEach(option=>{option.disabled=true;if(+option.dataset.answer===q.answer)option.classList.add('correct');});if(!correct)b.classList.add('wrong');$('quiz-score').textContent=`${state.score} correct`;$('quiz-feedback').textContent=(correct?'Correct. ':'The answer is '+q.options[q.answer]+'. ')+q.why;$('quiz-next').textContent=state.quizIndex===questions.length-1?'See results':'Next question';$('quiz-next').hidden=false;}));}
$('quiz-next').addEventListener('click',()=>{if(state.quizIndex===questions.length){state.quizIndex=0;state.score=0;quizRender();return;}state.quizIndex++;if(state.quizIndex<questions.length)quizRender();else{$('quiz-progress').textContent='COMPLETE';$('quiz-question').textContent=`You connected ${state.score} of ${questions.length} concepts.`;$('quiz-options').innerHTML='';$('quiz-feedback').textContent='Return to any experiment to explore a concept again, or repeat the questions.';$('quiz-next').textContent='Try again';}});
function resetAll(){cancel('story');cancel('command');state.race=null;state.buffer=0;state.lamp=false;state.device='temperature';state.queue=0;state.processed=0;state.vSettings={rooms:10,days:7,rate:20,bias:0,decision:false,formats:['numbers','events']};$('occupancy').value=0;$('temperature').value=25;$('automation').checked=true;$('connections').checked=false;$('internet').checked=true;document.querySelector('.network-scene').classList.remove('offline','commanding');$('network-status').textContent='Internet connected';$('buffer-count').textContent='0';networkLog('Ready. Send a reading or disconnect the internet to test buffering.');$('story').disabled=false;$('story-note').textContent='A short demonstration of sensing and action.';['validate','sort','aggregate'].forEach(id=>$(id).checked=false);$('latency').value=200;$('latency-out').textContent='200 ms';$('edge-internet').checked=true;$('edge-run').disabled=false;$('edge-result').textContent='Ready';$('cloud-result').textContent='Ready';$('cloud-result').classList.remove('late');resetEdgeDiagram();$('edge-note').textContent='Animation is slowed down for visibility. Timing values are illustrative, not measurements of real equipment.';state.quizIndex=0;state.score=0;pauseMotion(reducedMotion);roomUpdate();processUpdate();selectV('volume');quizRender();setView('classroom');}
$('reset-all').addEventListener('click',resetAll);
let last=performance.now(),velocityElapsed=0;
setInterval(()=>{const now=performance.now(),delta=Math.min(200,now-last);last=now;if(state.paused||document.hidden)return;state.clock+=delta;const due=state.tasks.filter(t=>t.due<=state.clock);state.tasks=state.tasks.filter(t=>t.due>state.clock);due.forEach(t=>t.fn());raceUpdate();if(state.view==='bigdata'&&state.v==='velocity'){velocityElapsed+=delta;if(velocityElapsed>=1000){velocityElapsed-=1000;const available=state.queue+state.vSettings.rate;state.processed+=Math.min(30,available);state.queue=Math.max(0,available-30);renderV();}}else velocityElapsed=0;},100);
roomUpdate();processUpdate();selectV('volume');quizRender();setView(location.hash.slice(1)||'classroom',false);pauseMotion(reducedMotion);
