'use strict';
// A guided lesson sits above the existing experiments. Free exploration remains available.
const guideState={mode:'guided',steps:{},done:false,busy:false,signal:null,generation:0};
const guide=document.createElement('section');guide.id='lesson-guide';guide.setAttribute('aria-label','Guided lesson');guide.innerHTML='<div class="guide-top"><span id="guide-progress"></span><button id="guide-back" class="quiet" disabled>← Previous</button><button id="lesson-mode" class="quiet" aria-pressed="false">Explore freely</button></div><div class="guide-body"><span id="guide-number" aria-hidden="true">1</span><div class="guide-copy"><h3 id="guide-title"></h3><p id="guide-instruction"></p><p id="guide-result" aria-live="polite"></p></div><div class="guide-actions"><button id="guide-watch" class="primary"></button><button id="guide-next" class="secondary" disabled>Next step →</button></div></div>';
document.querySelector('.lab-nav').after(guide);
const thermometer=document.createElement('div');thermometer.className='room-thermometer';thermometer.setAttribute('aria-hidden','true');thermometer.innerHTML='<div class="thermometer-track"><i></i></div><span>25 °C</span>';$('room').append(thermometer);
const gust=document.createElementNS('http://www.w3.org/2000/svg','svg');gust.classList.add('cooling-gust');gust.setAttribute('viewBox','0 0 100 100');gust.setAttribute('aria-hidden','true');gust.innerHTML='<path d="M10 10 Q50 20 35 50 T60 85"/><path d="M30 10 Q70 20 55 50 T80 85"/><path d="M50 10 Q90 20 75 50 T100 85"/>';$('room').append(gust);
const narrative=document.createElement('div');narrative.className='scene-narrative';narrative.setAttribute('aria-hidden','true');$('room').append(narrative);
const networkSvg=document.querySelector('.network-scene svg');
const guidedPacket=document.createElementNS('http://www.w3.org/2000/svg','circle');guidedPacket.id='guided-packet';guidedPacket.setAttribute('r','10');guidedPacket.setAttribute('fill','#d37b4c');guidedPacket.style.display='none';networkSvg.append(guidedPacket);
const networkMessage=document.createElement('div');networkMessage.className='message-bubble';networkMessage.textContent='';document.querySelector('.network-scene').append(networkMessage);
const lessons={
 classroom:[
  {title:'Let one student enter',instruction:'Watch the occupancy sensor notice someone. The lights should turn on.',action:'Let a student in',focus:'occupancy',setup:()=>{$('occupancy').value=0;$('temperature').value=25;$('automation').checked=true;state.device='occupancy';roomUpdate();},run:()=>{$('automation').checked=true;setRoom('occupancy',1);roomMoment('Someone enters','Presence detected');},test:()=>+$('occupancy').value>0&&state.lights,result:'The sensor senses presence. A local rule switches the lights on.'},
  {title:'Make the room warmer',instruction:'Raise the temperature above 27 °C. Watch the sensor reading and aircon.',action:'Warm the room to 30 °C',focus:'temperature',setup:()=>{state.device='temperature';roomUpdate();},run:()=>{$('automation').checked=true;if(+$('occupancy').value===0)$('occupancy').value=1;setRoom('temperature',25);animateTemperature(30);},test:()=>+$('temperature').value>27&&state.cooling,result:'The room is occupied and warm. The cooling rule now turns the aircon on.'},
  {title:'See the device act',instruction:'Look for the blue airflow. The aircon changes the physical room.',action:'Show sensing and action',focus:'aircon',setup:()=>{$('automation').checked=true;$('occupancy').value=1;$('temperature').value=30;state.device='aircon';roomUpdate();},run:()=>{roomMoment('30 °C sensed','Cooling command → airflow');$('room').classList.add('show-response');finishAfter(1800);},test:()=>false,result:'A sensor measures. An actuator acts. The aircon is the actuator here.'},
  {title:'Leave the room',instruction:'Remove the student. Watch the lights and cooling switch off.',action:'Let the student leave',focus:'occupancy',run:()=>{setRoom('occupancy',1);guideState.busy=true;schedule(700,()=>{setRoom('occupancy',0);roomMoment('The room is empty','Lights off · cooling off');guideState.busy=false;completeStep();},'guide');},test:()=>+$('occupancy').value===0&&!state.lights&&!state.cooling,result:'Occupancy data prevents unnecessary operation in an empty classroom.'}
 ],
 network:[
  {title:'Start with one reading',instruction:'Follow the orange dot from the temperature sensor to the gateway.',action:'Send a sensor reading',focus:'sensor',setup:()=>{$('internet').checked=true;state.buffer=0;$('buffer-count').textContent=0;document.querySelector('.network-scene').classList.remove('offline');$('network-status').textContent='Internet connected';},run:()=>flySignal('M210 95 Q330 95 420 180',$('temperature').value+' °C · Zigbee reading',1800),test:()=>false,result:'The device sends its reading using Zigbee. It arrives at the gateway.'},
  {title:'The gateway translates',instruction:'The gateway packages the reading into a message the platform can receive.',action:'Translate and forward',focus:'gateway',run:()=>flySignal('M560 180 L725 180',$('temperature').value+' °C · HTTPS / TLS',1800),test:()=>false,result:'The gateway bridges a supported device protocol and an internet protocol.'},
  {title:'The platform makes data visible',instruction:'Follow the message to the teacher’s dashboard.',action:'Show the reading in the app',focus:'platform',run:()=>flySignal('M865 180 L965 180','Dashboard updated · '+$('temperature').value+' °C',1800),test:()=>false,result:'The platform stores the reading. The app displays it to the teacher.'},
  {title:'Send an action back',instruction:'Follow a cooling command from the app, through the platform and gateway, to the aircon.',action:'Send a cooling command',focus:'command',run:()=>flySignal('M965 180 L865 180 L560 180 L490 228 Q490 285 585 345','Command · cooling ON',2600),test:()=>false,result:'Communication goes both ways: readings go up and commands come back.'},
  {title:'What if the internet drops?',instruction:'Send a reading while disconnected. The gateway keeps it until the connection returns.',action:'Disconnect and send',focus:'gateway',run:()=>{state.buffer=0;$('buffer-count').textContent='0';$('internet').checked=false;$('internet').dispatchEvent(new Event('change'));sendReading();networkMessage.textContent='Gateway buffer · 1 stored reading';},test:()=>state.buffer>0,result:'The gateway buffers this reading. Local classroom rules can still operate.'},
  {title:'Reconnect and deliver',instruction:'Restore the connection. Watch the buffered reading reach the platform.',action:'Restore the internet',focus:'platform',run:()=>{$('internet').checked=true;$('internet').dispatchEvent(new Event('change'));flySignal('M560 180 L725 180','Buffered reading delivered',1800);},test:()=>false,result:'The gateway uploads its buffered message and clears the buffer.'}
 ],
 processing:[
  {title:'Spot an impossible reading',instruction:'One reading says 20,000 °C. Validate the data and watch that record get flagged.',action:'Validate the readings',focus:'validate',setup:()=>{['validate','sort','aggregate'].forEach(id=>$(id).checked=false);processUpdate();},run:()=>toggleProcessing('validate'),test:()=>$('validate').checked,result:'Validation excludes the impossible reading. The mean becomes 25.4 °C.'},
  {title:'Put the readings in time order',instruction:'Sort the valid records. Watch them move into their timestamp order.',action:'Sort by time',focus:'sort',setup:()=>{$('validate').checked=true;$('sort').checked=false;$('aggregate').checked=false;processUpdate();},run:()=>toggleProcessing('sort'),test:()=>$('sort').checked,result:'The readings now follow time order. Sorting does not change the mean.'},
  {title:'Send a useful summary',instruction:'Combine the five valid readings into one batch mean.',action:'Make one summary',focus:'aggregate',setup:()=>{$('validate').checked=true;$('sort').checked=true;$('aggregate').checked=false;processUpdate();},run:()=>toggleProcessing('aggregate'),test:()=>$('aggregate').checked,result:'Five valid records become one summary: 25.4 °C. Fewer records travel onward.'}
 ],
 edge:[
  {title:'Race two response paths',instruction:'A robot must stop within 10 ms. Watch the local decision finish before the cloud trip.',action:'Compare edge and cloud',focus:'race',setup:()=>{$('latency').value=80;$('latency-out').textContent='80 ms';$('edge-internet').checked=true;},run:()=>{$('edge-run').click();finishAfter(4300);},test:()=>false,result:'Local response: 8 ms. Cloud response: 100 ms. Only the local response meets this example’s deadline.'},
  {title:'Try the same event offline',instruction:'Disconnect the internet, then run the comparison again.',action:'Disconnect and compare',focus:'offline',run:()=>{$('edge-internet').checked=false;$('edge-run').click();finishAfter(800);},test:()=>false,result:'The local response still works. The cloud cannot return a response while disconnected.'}
 ],
 bigdata:[
  {title:'Volume: collect for longer',instruction:'Watch the data store fill as one classroom collects readings for more days.',action:'Collect for 30 days',focus:'volume',setup:()=>{state.vSettings.rooms=1;state.vSettings.days=1;selectV('volume');},run:()=>growVolume(),test:()=>false,result:'More time means more accumulated records. This is Volume.'},
  {title:'Variety: add a different data form',instruction:'Add an image alongside numbers and events. Watch a new kind of data join the stream.',action:'Add a camera image',focus:'variety',setup:()=>{state.vSettings.formats=['numbers','events'];selectV('variety');},run:()=>{state.vSettings.formats.push('images');selectV('variety');finishAfter(1300);},test:()=>false,result:'Numbers, events and images have different forms. This is Variety.'},
  {title:'Velocity: speed up arrivals',instruction:'Send 80 readings each second to a processor that handles 30. Watch the queue grow.',action:'Speed up the stream',focus:'velocity',setup:()=>{state.queue=0;state.processed=0;state.vSettings.rate=20;selectV('velocity');},run:()=>{state.vSettings.rate=80;selectV('velocity');finishAfter(2500);},test:()=>false,result:'The arrival rate exceeds capacity, so a backlog grows. This is Velocity.'},
  {title:'Veracity: change sensor placement',instruction:'Move three sensors beside the cold aircon vent. Watch the reported mean fall.',action:'Move three sensors',focus:'veracity',setup:()=>{state.vSettings.bias=0;selectV('veracity');},run:()=>{state.vSettings.bias=3;selectV('veracity');finishAfter(1300);},test:()=>false,result:'The room is still 28 °C, but the mean becomes 24.4 °C. Placement affects trust. This is Veracity.'},
  {title:'Value: use the data to act',instruction:'The classroom is empty. Use occupancy data to stop unnecessary cooling.',action:'Use occupancy to decide',focus:'value',setup:()=>{state.vSettings.decision=false;selectV('value');},run:()=>{state.vSettings.decision=true;selectV('value');finishAfter(1300);},test:()=>false,result:'The decision avoids four unnecessary cooling hours in this example. This is Value.'}
 ]
};
function currentLesson(){return lessons[state.view]?.[guideState.steps[state.view]||0];}
function setRoom(id,value){$(id).value=value;roomUpdate();}
function roomMoment(first,second){narrative.textContent=first;narrative.classList.remove('moment');void narrative.offsetWidth;narrative.classList.add('moment');schedule(800,()=>narrative.textContent=second,'guide');}
function animateTemperature(target){guideState.busy=true;const start=+$('temperature').value;for(let i=1;i<=target-start;i++)schedule(i*230,()=>{setRoom('temperature',start+i);if(start+i===target){guideState.busy=false;roomMoment('30 °C detected','Cooling turns on');completeStep();}},'guide');if(start>=target){guideState.busy=false;completeStep();}}
function finishAfter(delay){guideState.busy=true;const duration=reducedMotion?150:delay;schedule(duration,()=>{guideState.busy=false;completeStep();},'guide');}
function flySignal(path,message,duration){guideState.busy=true;guidedPacket.style.display='block';networkMessage.textContent=message;const geometry=document.createElementNS('http://www.w3.org/2000/svg','path');geometry.setAttribute('d',path);guideState.signal={geometry,length:geometry.getTotalLength(),start:state.clock,duration:reducedMotion?150:duration};const p=geometry.getPointAtLength(0);guidedPacket.setAttribute('cx',p.x);guidedPacket.setAttribute('cy',p.y);finishAfter(duration);}
function growVolume(){guideState.busy=true;[3,7,14,21,30].forEach((day,i)=>schedule((i+1)*400,()=>{state.vSettings.days=day;renderV();if(i===4){guideState.busy=false;completeStep();}},'guide'));}
function toggleProcessing(id){const list=$('processed-readings');const before=new Map([...list.children].map(e=>[e.textContent.trim(),e.getBoundingClientRect().top]));$(id).checked=true;processUpdate();[...list.children].forEach(el=>{const old=before.get(el.textContent.trim());if(old!==undefined&&!reducedMotion)el.animate([{transform:`translateY(${old-el.getBoundingClientRect().top}px)`},{transform:'translateY(0)'}],{duration:900,easing:'ease-in-out'});});list.classList.remove('processing-flash');void list.offsetWidth;list.classList.add('processing-flash');if(id==='validate')all('.datum.invalid').forEach(e=>{if(!reducedMotion)e.animate([{transform:'translateX(0)'},{transform:'translateX(-8px)'},{transform:'translateX(8px)'},{transform:'translateX(0)'}],{duration:500});});finishAfter(1100);}
function syncRoomVisual(){const t=+$('temperature').value;thermometer.querySelector('span').textContent=t+' °C';thermometer.querySelector('i').style.height=Math.max(5,(t-18)/17*100)+'%';}
function focusLesson(){all('.network-node .node-focus').forEach(e=>e.classList.remove('node-focus'));all('.lesson-focus').forEach(e=>e.classList.remove('lesson-focus'));const step=currentLesson();document.body.dataset.lessonView=state.view;document.body.dataset.lessonFocus=step?.focus||'';const target=state.view==='classroom'?document.querySelector(`[data-device="${step?.focus}"]`):state.view==='processing'?$(step?.focus)?.closest('label'):null;if(target)target.classList.add('lesson-focus');if(state.view==='network'){// Highlight the device or service used in this step.
 const words=step?.focus==='sensor'?['Temperature']:step?.focus==='gateway'?['Gateway']:step?.focus==='platform'?['Platform','Teacher app']:['Teacher app','Platform','Gateway','Aircon'];all('.network-node text').forEach(text=>{const focused=words.includes(text.textContent);text.classList.toggle('node-focus',focused);if(focused)text.previousElementSibling?.classList.add('node-focus');});}
}
function completeStep(){if(guideState.mode!=='guided'||guideState.done)return;guideState.done=true;$('guide-result').textContent=currentLesson()?.result||'';$('guide-result').classList.add('visible');$('guide-next').disabled=false;$('guide-watch').disabled=false;$('guide-watch').textContent='Replay this step';guide.classList.add('step-complete');}
function renderGuide(setup=true){guideState.generation++;cancel('guide');if(guideState.mode==='guided'){cancel('story');$('story').disabled=false;}if((state.view!=='edge'||setup)&&state.race){state.race=null;$('edge-run').disabled=false;}guideState.signal=null;guidedPacket.style.display='none';guideState.busy=false;guideState.done=false;guide.classList.remove('step-complete');$('guide-result').textContent='';$('guide-result').classList.remove('visible');const sequence=lessons[state.view];guide.hidden=!sequence||guideState.mode!=='guided';document.body.classList.toggle('guided',guideState.mode==='guided');if(!sequence){focusLesson();return;}const i=guideState.steps[state.view]||0,step=sequence[i];$('guide-back').disabled=i===0;$('guide-progress').textContent=`GUIDED LESSON · ${i+1} OF ${sequence.length}`;$('guide-number').textContent=i+1;$('guide-title').textContent=step.title;$('guide-instruction').textContent=step.instruction;$('guide-watch').textContent=step.action;$('guide-watch').disabled=false;$('guide-next').disabled=true;$('guide-next').textContent=i<sequence.length-1?'Next step →':state.view==='bigdata'?'Try the quiz →':'Next lesson →';if(state.view==='network'&&i<=3){$('internet').checked=true;document.querySelector('.network-scene').classList.remove('offline');$('network-status').textContent='Internet connected';}if(setup&&step.setup)step.setup();networkMessage.textContent='';narrative.classList.remove('moment');focusLesson();syncRoomVisual();}
$('guide-watch').addEventListener('click',()=>{if(guideState.busy)return;guideState.done=false;guide.classList.remove('step-complete');$('guide-result').textContent='';$('guide-next').disabled=true;$('guide-watch').disabled=true;pauseMotion(false);const step=currentLesson();step.run();if(!guideState.busy)completeStep();});
$('guide-back').addEventListener('click',()=>{const i=guideState.steps[state.view]||0;if(i>0){guideState.steps[state.view]=i-1;renderGuide();}});
$('guide-next').addEventListener('click',()=>{if(!guideState.done)return;const sequence=lessons[state.view],i=guideState.steps[state.view]||0;if(i<sequence.length-1){guideState.steps[state.view]=i+1;renderGuide();}else{const order=['classroom','network','processing','edge','bigdata','challenge'];setView(order[order.indexOf(state.view)+1]);}guide.scrollIntoView({block:'nearest',behavior:reducedMotion?'instant':'smooth'});});
function setMode(mode){guideState.mode=mode;document.body.classList.toggle('guided',mode==='guided');$('lesson-mode').textContent=mode==='guided'?'Explore freely':'Back to guided lesson';$('lesson-mode').setAttribute('aria-pressed',String(mode==='explore'));$('detail-mode').textContent=mode==='guided'?'More detail & free exploration':'Return to guided lesson';renderGuide(false);}
$('lesson-mode').addEventListener('click',()=>setMode('explore'));
const detailMode=document.createElement('button');detailMode.id='detail-mode';detailMode.className='quiet';detailMode.textContent='More detail & free exploration';document.querySelector('.lab-nav').after(detailMode);detailMode.addEventListener('click',()=>setMode(guideState.mode==='guided'?'explore':'guided'));
const baseSetView=setView;setView=function(view,updateHash=true){baseSetView(view,updateHash);const tab=document.querySelector('[data-view="'+state.view+'"]');if(tab)document.querySelector('.lab-nav').scrollLeft=tab.offsetLeft-document.querySelector('.lab-nav').offsetLeft;renderGuide();};
$('reset-all').addEventListener('click',()=>{guideState.steps={};setMode('guided');renderGuide();});
['input','change'].forEach(name=>document.addEventListener(name,event=>{syncRoomVisual();if(guideState.mode==='guided'&&!guideState.busy&&currentLesson()?.test())completeStep();}));
setInterval(()=>{syncRoomVisual();const signal=guideState.signal;if(signal&&!state.paused){const fraction=Math.min(1,(state.clock-signal.start)/signal.duration);const p=signal.geometry.getPointAtLength(signal.length*fraction);guidedPacket.setAttribute('cx',p.x);guidedPacket.setAttribute('cy',p.y);if(fraction===1)guideState.signal=null;}if(guideState.done||guideState.mode!=='guided'||guideState.busy)return;},60);
renderGuide();
